### ISSUE TITLE
Please add support for Kraken 240 

### ISSUE THREAD

**Issue by marcomistretta** [liquidctl/liquidctl#624] opened 2023-08-18 01:45 UTC
### Device type

AIO liquid cooler, Kraken 240 (no rgb version)

### Product page

https://nzxt.com/product/kraken-240

### First-party software

NZXT CAM

### What monitoring functionality does the device support?

temperatures, fan/pump speeds or duty cycles

### What configuration functionality does the device support?

fan/pump speeds or duty cycles, lighting of embedded LEDs, lighting of accessories like RGB fans or LED strips

### Can you help with implementing or testing the changes needed for liquidctl to support this device?

testing changes on Linux

**Comment by aleksamagicka** [comment] 2023-11-24 17:34
You didn't list the USB product ID, so I'll guess that it's `0x300E`. Support for that landed in https://github.com/liquidctl/liquidctl/pull/605. Can you please try and see if it works for you?

**Comment by Silverwolf-3D** [comment] 2023-12-14 15:14
Does this help I did a lsusb 
`Bus 001 Device 002: ID 1e71:2012 NZXT NZXT RGB Controller`
`Bus 003 Device 002: ID 1e71:300e NZXT NZXT Kraken Base`
I got one also, but I am a linux newbie so hope this helps.

**Comment by lanceofwhichwedream** [comment] 2024-01-28 04:48
Going to +1 this thread, looks like on windows the Kraken 240 presents itself like this

> USB\VID_1E71&PID_300E&MI_00
Vendor id 1e71
Product id 300e

I'd be super down to test on windows and I can provide any additional information you might need @aleksamagicka

**Comment by aleksamagicka** [comment] 2024-01-28 06:48
Support for that Kraken in liquidctl has been merged in [October](https://github.com/liquidctl/liquidctl/commit/846ac5f5aa9d5484e8ed1d549fd2478bbf51fdd8). Please retry with the [Git version](https://github.com/liquidctl/liquidctl#installing-from-pypi-or-github) for the time being.

**Comment by lanceofwhichwedream** [comment] 2024-01-28 23:15
Will do, thank you for the info. I'll report back if it was successful.

**Comment by renhiyama** [comment] 2024-02-24 12:05
@lanceofwhichwedream can you report back whether you got it working successfully or not? I need to buy a water cooler, and this cooler costs $30 less than kraken x53, so if its successful, I could be getting a better product with more features (lcd) and $30 cheaper 😅

**Comment by naggie** [comment] 2024-03-31 08:29
I can confirm it works on fb697e05c00a9ed8818d88a25d6202f46782d811 (latest master as of yesterday)

...however, after overnight using the python library to control pump and fan speed I get a "device has no longid" error

![image](https://github.com/liquidctl/liquidctl/assets/208440/289dce24-959e-4787-bdeb-6673563fd76a)

Same with liquidctl status: 
![image](https://github.com/liquidctl/liquidctl/assets/208440/83140e78-eb9d-44e2-ac06-761eead097ff)

**Comment by naggie** [comment] 2024-04-01 08:37
It crashed again overnight, more than 12 hours after re-plugging it.

There's something suspicious in teh 
![image](https://github.com/liquidctl/liquidctl/assets/208440/e997d9d2-f9c3-4903-b0c1-f99f4b9b48c4)

The LCD on the Kraken is also stuck.

**Comment by aleksamagicka** [comment] 2024-04-02 21:47
> Note also in windows I had to replug the device to get CAM to recognise it. Perhaps I have a dud?

From what you're describing, it seems plausible to me (but I've never had this happen to concur). Maybe check that the cables are snug? Perhaps the connector isn't soldered correctly or is otherwise damaged, and the firmware disconnects after failed packets.

I'm guessing that other devices on internal USB work fine?

**Comment by naggie** [comment] 2024-04-03 12:02
I actually spoke to soon -- I forgot the sudo (or udev rules) when I checked it before going to sleep :facepalm: 

It's been running for 15h after the firmware update without a problem. I'll report back tomorrow, if it's still working then the firmware update may have fixed it. 

Otherwise yes indeed the internal USB is fine with other devices and the cables seem ok. Thanks for the reply

**Comment by naggie** [comment] 2024-04-04 19:03
OK it's been nearly 24h, I can confidently say the firmware update fixed the problem. I've made a PR to update the readme.

**Comment by robzombie91** [comment] 2024-04-18 00:36
just to add to this, my kraken 240 doesnt display anything when doing liquid list, and the pip version shows this error ValueError: The device has no langid (permission issue, no string descriptors supported or device error)
lsusb does show it as Bus 001 Device 006: ID 1e71:300e NZXT NZXT Kraken Base

**Comment by naggie** [comment] 2024-04-18 07:21
Have you tried updating the firmware using NZXT Cam? Also, I presume you're using udev rules or sudo.

**Comment by robzombie91** [comment] 2024-04-18 11:07
Yeah I figured out that sudoing would let me run the script successfully

**Closed** 2024-12-16 20:49 UTC
Labels: new device
