### ISSUE TITLE
Setting LED colour on Corsair H100i Platinum SE only sets colour for pump and one fan.

### ISSUE THREAD

**Issue by Priva28** [liquidctl/liquidctl#267] opened 2021-01-22 05:35 UTC
Pretty much the title. Fan/pump control works great as expected but setting RGB colour seems to only be half working. 

Running `sudo liquidctl initialize all` shows this:
```
Corsair H100i Platinum SE (experimental)
└── Firmware version    1.1.15
```

Running `sudo liquidctl set led color off` works and turns all of the LEDs off for the pump, fan 1 and fan 2.

But running `sudo liquidctl set led color fixed ffffff` only sets the colour for the pump and fan 1 LED while fan 2 LED remains off.

I'm running a plain Debian 10 Buster.
![IMG_2828](https://user-images.githubusercontent.com/40876121/105450822-6a84b600-5ccf-11eb-9a61-9b750c0361fe.jpg)

**Comment by jonasmalacofilho** [comment] 2021-01-22 07:03
Can you provide the output of `liquidctl list --debug`?

Additionally, do you know how many LEDs are in the pump and in each fan?

**Comment by Priva28** [comment] 2021-01-22 08:08
Sure:
```
[DEBUG] liquidctl.cli: running liquidctl v1.4.2
[DEBUG] liquidctl.driver.usb: searching HidapiBus (api=hidraw, drivers=[CorsairHidPsu, HydroPlatinum, Kraken2, KrakenX3, KrakenZ3, NzxtEPsu, RgbFusion2, SmartDevice, SmartDevice2, _CommonSmartDeviceDriver])
[DEBUG] liquidctl.driver.usb: probing drivers for device 1b1c:0c19
[DEBUG] liquidctl.driver.usb: instanced driver for Corsair H100i Platinum SE (experimental)
[DEBUG] liquidctl.driver.usb: probing drivers for device 1462:7c75
[DEBUG] liquidctl.driver.usb: searching PyUsbBus (drivers=[Hydro690Lc, Legacy690Lc, Modern690Lc, _CommonAsetekDriver])
[DEBUG] liquidctl.driver.usb: probing drivers for device 1058:25e3
[DEBUG] liquidctl.driver.usb: probing drivers for device 1d6b:0003
[DEBUG] liquidctl.driver.usb: probing drivers for device 0bc2:231a
[DEBUG] liquidctl.driver.usb: probing drivers for device 1a86:7523
[DEBUG] liquidctl.driver.usb: probing drivers for device 1462:7c75
[DEBUG] liquidctl.driver.usb: probing drivers for device 1b1c:0c19
[DEBUG] liquidctl.driver.usb: probing drivers for device 05e3:0608
[DEBUG] liquidctl.driver.usb: probing drivers for device 1058:10a2
[DEBUG] liquidctl.driver.usb: probing drivers for device 1d6b:0002
Device ID 0: Corsair H100i Platinum SE (experimental)
├── Vendor ID: 0x1b1c
├── Product ID: 0x0c19
├── Release number: 0x0100
├── Bus: hid
├── Address: /dev/hidraw6
└── Driver: HydroPlatinum using module hidraw
[DEBUG] liquidctl.cli: hierarchy: UsbHidDriver, BaseUsbDriver, BaseDriver; HidapiDevice
```

**Comment by MarshallAsch** [comment] 2021-01-22 19:45
This should be an easy fix that Im working on. The H100i Platinum SE uses the LL fans that have 16 leds on each of them.

**Comment by MarshallAsch** [comment] 2021-01-22 21:33
This is a duplicate of #242. 

closing.

**Closed by MarshallAsch** 2021-01-22 21:33 UTC
Labels: bug
