### ISSUE TITLE
Aorus liquid cooler?

### ISSUE THREAD

**Issue by Jackiiiii** [liquidctl/liquidctl#247] opened 2020-12-25 13:23 UTC
Hello, does it not support Aorus liquid cooler? and if not... is there anyway i can use my display and setting for Fan and Pump?... on linux..

i m searching now like last 3 days....

**Comment by jonasmalacofilho** [comment] 2020-12-25 14:06
> Hello, does it not support Aorus liquid cooler? 

Not yet, see #167.

> is there anyway i can use my display and setting for Fan and Pump?... on linux..

I'm not sure.

---

Closing as a duplicate of #167.

**Closed by jonasmalacofilho** 2020-12-25 14:06 UTC
Labels: duplicate
